version: "3.9"

services:
  scraper:
    build:
      dockerfile: Dockerfile
      context: build
    volumes:
      - ./scripts:/etc/app
      - ./data:/etc/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$IP
    command: /entrypoint.sh
